name: Playwright Tests
on:
  push:
    branches: [main, master] # run the scripts on each commit
  pull_request:
    branches: [main, master] # run the scripts on pull request
  repository_dispatch:  
    types: [trigger-workflow] # can be used for triggering workflow in other directories
jobs:
  test:
    timeout-minutes: 60
    runs-on: [ubuntu-latest] # runner name were the script should run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          ref: ${{ github.event.client_payload.sha }}
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run GUI Automation tests
        run: npm test
        env:
          USERNAME: ${{ secrets.USERNAME }}       #username can be stored in github secrets
          PASSWORD: ${{ secrets.PASSWORD }}       #password can be stored in github secrets
          URL: ${{ secrets.API_URL }}         #URL can be stored in github secrets
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./test-results/  #store the test results as archive
          retention-days: 30
   

      
